name: Update README.md

on:
  schedule:
    - cron: '0/6 * * * *'
  workflow_dispatch:

jobs:
  update-discourse:
    name: Update this repo's README with latest posts on gohugo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          max_post_count: 4
          feed_list: "https://discourse.gohugo.io/u/davidsneighbour/activity.rss"
          comment_tag_name: "DISCOURSE"
          template: "$newline- ($date) [$title]($url)"
          date_format: "mmmm d, yyyy 'at' h:MM TT"
          commit_message: "chore: update README.md with latest gohugo.io posts"
  update-kollitsch:
    name: Update this repo's README with latest blog posts on kollitsch.de
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: "KOLLITSCH"
          feed_list: "https://kollitsch.de/rss.xml"
