name: Update README.md

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@1.7.1
        name: Load latest blog posts on kollitsch.dev
        with:
          comment_tag_name: "KOLLITSCH"
          feed_list: "https://kollitsch.dev/rss.xml"
