name: Update README.md

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gautamkrishnar/blog-post-workflow@v1
        name: Load latest blog posts on kollitsch.dev
        with:
          comment_tag_name: "KOLLITSCH"
          max_post_count: 10
          feed_list: "http://kollitsch.dev/rss.xml"
          template: "$newline- [$date] **[$title]($url)**$newline$newline  $description"
          date_format: "yyyy-mm-dd"
          description_max_length: 200
