name: Update README.md

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest posts on gohugo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          max_post_count: 4
          feed_list: "https://discourse.gohugo.io/u/pkollitsch/activity.rss"
          comment_tag_name: "DISCOURSE"
          template: "$newline- ($date) [$title]($url)"
          date_format: "mmmm d, yyyy \a\t h:MM TT"
          commit_message: "chore: update README.md with latest gohugo.io posts"
